# Generated by Django 5.1.2 on 2024-10-21 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='categoria_image',
            field=models.ImageField(blank=True, null=True, upload_to='categorias/'),
        ),
    ]
