# Generated by Django 5.1.2 on 2024-10-21 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aromas', '0001_initial'),
        ('categorias', '0001_initial'),
        ('formatos', '0001_initial'),
        ('grupo_etario', '0001_initial'),
        ('ingredientes', '0001_initial'),
        ('proveedores', '0001_initial'),
        ('tipo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad', models.PositiveIntegerField()),
                ('descripcion', models.TextField()),
                ('aroma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aromas.aroma')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categorias.categoria')),
                ('formato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formatos.formato')),
                ('grupo_etario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grupo_etario.grupoetario')),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingredientes.ingrediente')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedores.proveedor')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tipo.tipo')),
            ],
        ),
    ]
