# Generated by Django 5.1.2 on 2024-10-21 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='producto_image',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
    ]
